### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by SemenMartynov** [Gradergage/JsonValidator#5]
Go ahead and implement task 2

**Comment by Gradergage** [comment]
I have a problem with building, 
```
gradergage@ubuntu:~/Projects/trpo/JsonValidator$ sudo bash gradlew createDockerImage
[sudo] password for gradergage: 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'JsonValidator'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download gradle-docker-plugin.jar (com.bmuschko:gradle-docker-plugin:3.2.1)
      > Could not get resource 'https://jcenter.bintray.com/com/bmuschko/gradle-docker-plugin/3.2.1/gradle-docker-plugin-3.2.1.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/bmuschko/gradle-docker-plugin/3.2.1/gradle-docker-plugin-3.2.1.jar'.
            > sun.security.validator.ValidatorException: No trusted certificate found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

Build file can't download the plugin. The Solving in progress, but i think, that main problem at my side, i tryed to update certs, but it doesn't works. Maybe you able to build it?

**Comment by Gradergage** [comment]
Another computer of my colleague has built the project, but i am still solving cert problem at my virtual system. So, i expect, that this is not real trouble that disturb to pass to the next task. I will fix it in future just for interest
![rd0vb9dsnkc](https://user-images.githubusercontent.com/8627307/34910418-fe580bc8-f8c5-11e7-9bee-28d13c022137.jpg)

**Comment by SemenMartynov** [comment]
1. fix gradlew permission (it should be executable)
2. remove sudo call from documentation
3. fix image tag (the capital letter in the documentation)

**Comment by Gradergage** [comment]
Updated permissions using `git update-index --chmod=+x gradlew`
All fixed

**Comment by SemenMartynov** [comment]
When i follow your documentation:
1. gradlew DO NOT require sudo
2. I see extra space in gradlew call
```
$ ./ gradlew createDockerImage
-bash: ./: Is a directory
```
3. Can't build project
```
$ ./gradlew createDockerImage                                                                                     
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :createDockerImage 
Building image using context '/media/basket/home/Documents/git/students/JsonValidator'.
Using tag 'Validator' for image.

[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Error parsing reference: \"Validator\" is not a valid repository/tag: repository name must be lowercase"}

        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createDockerImage'.
> {"message":"Error parsing reference: \"Validator\" is not a valid repository/tag: repository name must be lowercase"}


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
4 actionable tasks: 4 executed

```

Please test everything on you side before my checking. Otherwise it will take a very long time.

**Comment by Gradergage** [comment]
Im have changed the tag to uppercase, as you wanted, why tag must be in this format?

**Comment by Gradergage** [comment]
Ok, all fixed

**Comment by SemenMartynov** [comment]
No, I didn't want you to use capital letters for tag, I just pointed that you use сapital letter in documentation, and this will be an issue because the letter's case is make a sense.

**Comment by SemenMartynov** [comment]
Checked
